import { SelectOption } from "@/components/shared/Selectbox"

export const POPULAR_HOBBIES = [
    { label: 'Gaming' },
    { label: 'Technik' },
    { label: 'Autos' },
    { label: 'Events' },
    { label: 'Mode' },
    { label: 'Essen & Trinken' },
    { label: 'Fitness' },
    { label: 'Sport' },
    { label: 'Musik' },
    { label: 'Reisen' },
    { label: 'Haustiere' },
    { label: 'Filme & Serien' },
    { label: 'Lesen' },
    { label: 'Kunst' },
    { label: 'Fotografie' },
    { label: 'Natur & Outdoor' },
    { label: 'Wellness' },
    { label: 'Brettspiele' },
    { label: 'Skaten & BMX' },
    { label: 'Nachhaltigkeit' },
]

export const SCHOOLS = [
    //Oberschulen
    { "id": 1, "name": "125. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 2, "name": "16. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 3, "name": "20. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 4, "name": "205. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 5, "name": "35. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 6, "name": "55. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 7, "name": "56. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 8, "name": "56. Schule - Oberschule der Stadt Leipzig - Schulteil Martin-Herrmann-Straße", "type": "Oberschule", "isPrivate": false },
    { "id": 9, "name": "68. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 10, "name": "84. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 11, "name": "94. Schule - Oberschule im Schulzentrum Grünau der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 12, "name": "Aktive Schule Leipzig - Freie Oberschule", "type": "Freie Oberschule", "isPrivate": true },
    { "id": 13, "name": "Apollonia-von-Wiedebach-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 14, "name": "Bischöfliches Maria-Montessori-Schulzentrum Leipzig Oberschule", "type": "Oberschule", "isPrivate": true },
    { "id": 15, "name": "Carl-Friedrich-Goerdeler-Oberschule Leipzig", "type": "Oberschule", "isPrivate": true },
    { "id": 16, "name": "Caroline-Neuber-Schule, Oberschule im Deutsch-Französischen Bildungszentrum der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 17, "name": "Christian-Gottlob-Frege-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 18, "name": "Denis-Diderot-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 19, "name": "Evangelisches Schulzentrum Leipzig Oberschule", "type": "Oberschule", "isPrivate": true },
    { "id": 20, "name": "Freie Oberschule Gohlis - Schulen für gemeinschaftliches Lernen e.V.", "type": "Freie Oberschule", "isPrivate": true },
    { "id": 21, "name": "Freie Schule Leipzig e.V.", "type": "Freie Schule", "isPrivate": true },
    { "id": 22, "name": "Freie Waldorfschule Leipzig", "type": "Waldorfschule", "isPrivate": true },
    { "id": 23, "name": "Georg-Schumann-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 24, "name": "Geschwister-Scholl-Schule Liebertwolkwitz - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 25, "name": "Heinrich-Pestalozzi-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 26, "name": "Helmholtzschule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 27, "name": "Karl Schubert Schule Leipzig - Freie Waldorfschule", "type": "Waldorfschule", "isPrivate": true },
    { "id": 28, "name": "Klaus-Gottschalk-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 29, "name": "Leipzig International School", "type": "Internationale Schule", "isPrivate": true },
    { "id": 30, "name": "Lene-Voigt-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 31, "name": "Nachbarschaftsschule - Grund- und Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 32, "name": "Oberschule Gohlis", "type": "Freie Oberschule", "isPrivate": true },
    { "id": 33, "name": "Paul-Robeson-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 34, "name": "Petrischule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 35, "name": "Rahn Education Freie Oberschule Leipzig", "type": "Freie Oberschule", "isPrivate": true },
    { "id": 36, "name": "Rahn Education Freie Oberschule Leipzig - Schulteil Südvorstadt", "type": "Freie Oberschule", "isPrivate": true },
    { "id": 37, "name": "Rosa-Parks-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 38, "name": "Rudi-Glöckner-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 39, "name": "Schule am Adler - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 40, "name": "Schule am Barnet-Licht-Platz - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 41, "name": "Schule am Weißeplatz - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 42, "name": "Schule Georg-Schwarz-Str. - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 43, "name": "Schule Hainbuchenstraße - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 44, "name": "Schule Höltystraße - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 45, "name": "Schule Ihmelsstraße - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 46, "name": "Schule Mölkau - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 47, "name": "Schule Paunsdorf - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 48, "name": "Schule Portitz - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 49, "name": "Schule Ratzelstraße - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 50, "name": "Schule Wiederitzsch - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 51, "name": "Sportoberschule Leipzig - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 52, "name": "TÜV Rheinland Oberschule Leipzig", "type": "Freie Oberschule", "isPrivate": true },
    // Gymnasien
    { "id": 53, "name": "Anton-Philipp-Reclam-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 54, "name": "BIP-Kreativitätsgymnasium Leipzig", "type": "Gymnasium", "isPrivate": true },
    { "id": 55, "name": "Bischöfliches Maria-Montessori-Schulzentrum Gymnasium", "type": "Gymnasium", "isPrivate": true },
    { "id": 56, "name": "Evangelisches Schulzentrum Leipzig Gymnasium", "type": "Gymnasium", "isPrivate": true },
    { "id": 57, "name": "Freie Waldorfschule Leipzig", "type": "Waldorfschule", "isPrivate": true },
    { "id": 58, "name": "Friedrich-Arnold-Brockhaus-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 59, "name": "Friedrich-Schiller-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 60, "name": "Georg-Christoph-Lichtenberg-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 61, "name": "Gerda-Taro-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 62, "name": "Goethe-Gymnasium Leipzig", "type": "Gymnasium", "isPrivate": false },
    { "id": 63, "name": "Gustav-Hertz-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 64, "name": "Gymnasium Engelsdorf", "type": "Gymnasium", "isPrivate": false },
    { "id": 65, "name": "Humboldt-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 66, "name": "Immanuel-Kant-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 67, "name": "Johanna-Moosdorf-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 68, "name": "Johannes-Kepler-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 69, "name": "Karl Schubert Schule Leipzig - Freie Waldorfschule", "type": "Waldorfschule", "isPrivate": true },
    { "id": 70, "name": "Leibnizschule", "type": "Gymnasium", "isPrivate": false },
    { "id": 71, "name": "Louise-Otto-Peters-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 72, "name": "Marie-Curie-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 73, "name": "Max-Klinger-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 74, "name": "Neue Nikolaischule", "type": "Gymnasium", "isPrivate": false },
    { "id": 75, "name": "Rahn Education Musikalisch-Sportliches Gymnasium", "type": "Gymnasium", "isPrivate": true },
    { "id": 76, "name": "Robert-Schumann-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 77, "name": "Sächsisches Landesgymnasium für Sport Leipzig", "type": "Gymnasium", "isPrivate": false },
    { "id": 78, "name": "Schule am Palmengarten", "type": "Gymnasium", "isPrivate": false },
    { "id": 79, "name": "Schule Hauptbahnhof-Westseite", "type": "Gymnasium", "isPrivate": false },
    { "id": 80, "name": "Schule Ihmelsstraße", "type": "Gymnasium", "isPrivate": false },
    { "id": 81, "name": "Schule Schraderhaus", "type": "Gymnasium", "isPrivate": false },
    { "id": 82, "name": "Thomasschule", "type": "Gymnasium", "isPrivate": false },
    { "id": 83, "name": "Werner-Heisenberg-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 84, "name": "Wilhelm-Ostwald-Schule", "type": "Gymnasium", "isPrivate": false },
    // Gemeinschaftsschulen
    { "id": 85, "name": "Leipziger Modellschule Gemeinschaftsschule", "type": "Gemeinschaftsschule", "isPrivate": true },
    { "id": 86, "name": "Schule am Dösner Weg - Gemeinschaftsschule der Stadt Leipzig", "type": "Gemeinschaftsschule", "isPrivate": false },
]

export const MAX_HOBBIES = 5

export const MAX_BYTES = 5 * 1024 * 1024

export const BUCKET = 'avatars'

export const DAY_OPTIONS: SelectOption[] = Array.from({ length: 31 }, (_, i) => {
    const d = i + 1
    return { value: String(d).padStart(2, '0'), label: String(d) }
})
  
export const MONTH_LABELS = [
    'Januar',
    'Februar',
    'März',
    'April',
    'Mai',
    'Juni',
    'Juli',
    'August',
    'September',
    'Oktober',
    'November',
    'Dezember',
] as const
  
export const MONTH_OPTIONS: SelectOption[] = MONTH_LABELS.map((m, i) => ({
    value: String(i + 1).padStart(2, '0'),
    label: m,
}))

export const GENDER_OPTIONS: SelectOption[] = [
    { value: 'female', label: 'Weiblich' },
    { value: 'male', label: 'Männlich' },
    { value: 'diverse', label: 'Divers' },
    { value: 'prefer_not_to_say', label: 'Keine Angabe' },
]

export const RELATIONSHIP_OPTIONS: SelectOption[] = [
    { value: 'single', label: 'Single' },
    { value: 'relationship', label: 'Vergeben' },
    { value: 'prefer_not_to_say', label: 'Keine Angabe' },
]

export const GRADELEVEL_OPTIONS: SelectOption[] = [
    { value: '12', label: '12' },
    { value: '11', label: '11' },
    { value: '10', label: '10' },
    { value: '9', label: '9' },
    { value: '8', label: '8' },
    { value: '7', label: '7' },
    { value: '6', label: '6' },
    { value: '5', label: '5' },
    { value: '4', label: '4' },
    { value: '3', label: '3' },
    { value: '2', label: '2' },
    { value: '1', label: '1' },
]

export const AVERAGEMARK_OPTIONS: SelectOption[] = [
    { value: '1.0', label: '1.0' },
    { value: '1.1', label: '1.1' },
    { value: '1.2', label: '1.2' },
    { value: '1.3', label: '1.3' },
    { value: '1.4', label: '1.4' },
    { value: '1.5', label: '1.5' },
    { value: '1.6', label: '1.6' },
    { value: '1.7', label: '1.7' },
    { value: '1.8', label: '1.8' },
    { value: '1.9', label: '1.9' },
    { value: '2.0', label: '2.0' },
    { value: '2.1', label: '2.1' },
    { value: '2.2', label: '2.2' },
    { value: '2.3', label: '2.3' },
    { value: '2.4', label: '2.4' },
    { value: '2.5', label: '2.5' },
    { value: '2.6', label: '2.6' },
    { value: '2.7', label: '2.7' },
    { value: '2.8', label: '2.8' },
    { value: '2.9', label: '2.9' },
    { value: '3.0', label: '3.0' },
    { value: '3.1', label: '3.1' },
    { value: '3.2', label: '3.2' },
    { value: '3.3', label: '3.3' },
    { value: '3.4', label: '3.4' },
    { value: '3.5', label: '3.5' },
    { value: '3.6', label: '3.6' },
    { value: '3.7', label: '3.7' },
    { value: '3.8', label: '3.8' },
    { value: '3.9', label: '3.9' },
    { value: '4.0', label: '4.0' },
    { value: '4.1', label: '4.1' },
    { value: '4.2', label: '4.2' },
    { value: '4.3', label: '4.3' },
    { value: '4.4', label: '4.4' },
    { value: '4.5', label: '4.5' },
    { value: '4.6', label: '4.6' },
    { value: '4.7', label: '4.7' },
    { value: '4.8', label: '4.8' },
    { value: '4.9', label: '4.9' },
    { value: '5.0', label: '5.0' },
    { value: '5.1', label: '5.1' },
    { value: '5.2', label: '5.2' },
    { value: '5.3', label: '5.3' },
    { value: '5.4', label: '5.4' },
    { value: '5.5', label: '5.5' },
    { value: '5.6', label: '5.6' },
    { value: '5.7', label: '5.7' },
    { value: '5.8', label: '5.8' },
    { value: '5.9', label: '5.9' },
    { value: '6.0', label: '6.0' },
]