export const POPULAR_HOBBIES = [
    { label: 'Gaming' },
    { label: 'Technik' },
    { label: 'Autos' },
    { label: 'Events' },
    { label: 'Mode' },
    { label: 'Essen & Trinken' },
    { label: 'Fitness' },
    { label: 'Sport' },
    { label: 'Musik' },
    { label: 'Reisen' },
    { label: 'Haustiere' },
    { label: 'Filme & Serien' },
    { label: 'Lesen' },
    { label: 'Kunst' },
    { label: 'Fotografie' },
    { label: 'Natur & Outdoor' },
    { label: 'Wellness' },
    { label: 'Brettspiele' },
    { label: 'Skaten & BMX' },
    { label: 'Nachhaltigkeit' },
]

export const SCHOOLS = [
    //Oberschulen
    { "id": 1, "name": "125. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 2, "name": "16. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 3, "name": "20. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 4, "name": "205. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 5, "name": "35. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 6, "name": "55. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 7, "name": "56. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 8, "name": "56. Schule - Oberschule der Stadt Leipzig - Schulteil Martin-Herrmann-Straße", "type": "Oberschule", "isPrivate": false },
    { "id": 9, "name": "68. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 10, "name": "84. Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 11, "name": "94. Schule - Oberschule im Schulzentrum Grünau der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 12, "name": "Aktive Schule Leipzig - Freie Oberschule", "type": "Freie Oberschule", "isPrivate": true },
    { "id": 13, "name": "Apollonia-von-Wiedebach-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 14, "name": "Bischöfliches Maria-Montessori-Schulzentrum Leipzig Oberschule", "type": "Oberschule", "isPrivate": true },
    { "id": 15, "name": "Carl-Friedrich-Goerdeler-Oberschule Leipzig", "type": "Oberschule", "isPrivate": true },
    { "id": 16, "name": "Caroline-Neuber-Schule, Oberschule im Deutsch-Französischen Bildungszentrum der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 17, "name": "Christian-Gottlob-Frege-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 18, "name": "Denis-Diderot-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 19, "name": "Evangelisches Schulzentrum Leipzig Oberschule", "type": "Oberschule", "isPrivate": true },
    { "id": 20, "name": "Freie Oberschule Gohlis - Schulen für gemeinschaftliches Lernen e.V.", "type": "Freie Oberschule", "isPrivate": true },
    { "id": 21, "name": "Freie Schule Leipzig e.V.", "type": "Freie Schule", "isPrivate": true },
    { "id": 22, "name": "Freie Waldorfschule Leipzig", "type": "Waldorfschule", "isPrivate": true },
    { "id": 23, "name": "Georg-Schumann-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 24, "name": "Geschwister-Scholl-Schule Liebertwolkwitz - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 25, "name": "Heinrich-Pestalozzi-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 26, "name": "Helmholtzschule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 27, "name": "Karl Schubert Schule Leipzig - Freie Waldorfschule", "type": "Waldorfschule", "isPrivate": true },
    { "id": 28, "name": "Klaus-Gottschalk-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 29, "name": "Leipzig International School", "type": "Internationale Schule", "isPrivate": true },
    { "id": 30, "name": "Lene-Voigt-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 31, "name": "Nachbarschaftsschule - Grund- und Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 32, "name": "Oberschule Gohlis", "type": "Freie Oberschule", "isPrivate": true },
    { "id": 33, "name": "Paul-Robeson-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 34, "name": "Petrischule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 35, "name": "Rahn Education Freie Oberschule Leipzig", "type": "Freie Oberschule", "isPrivate": true },
    { "id": 36, "name": "Rahn Education Freie Oberschule Leipzig - Schulteil Südvorstadt", "type": "Freie Oberschule", "isPrivate": true },
    { "id": 37, "name": "Rosa-Parks-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 38, "name": "Rudi-Glöckner-Schule - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 39, "name": "Schule am Adler - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 40, "name": "Schule am Barnet-Licht-Platz - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 41, "name": "Schule am Weißeplatz - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 42, "name": "Schule Georg-Schwarz-Str. - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 43, "name": "Schule Hainbuchenstraße - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 44, "name": "Schule Höltystraße - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 45, "name": "Schule Ihmelsstraße - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 46, "name": "Schule Mölkau - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 47, "name": "Schule Paunsdorf - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 48, "name": "Schule Portitz - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 49, "name": "Schule Ratzelstraße - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 50, "name": "Schule Wiederitzsch - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 51, "name": "Sportoberschule Leipzig - Oberschule der Stadt Leipzig", "type": "Oberschule", "isPrivate": false },
    { "id": 52, "name": "TÜV Rheinland Oberschule Leipzig", "type": "Freie Oberschule", "isPrivate": true },
    // Gymnasien
    { "id": 53, "name": "Anton-Philipp-Reclam-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 54, "name": "BIP-Kreativitätsgymnasium Leipzig", "type": "Gymnasium", "isPrivate": true },
    { "id": 55, "name": "Bischöfliches Maria-Montessori-Schulzentrum Gymnasium", "type": "Gymnasium", "isPrivate": true },
    { "id": 56, "name": "Evangelisches Schulzentrum Leipzig Gymnasium", "type": "Gymnasium", "isPrivate": true },
    { "id": 57, "name": "Freie Waldorfschule Leipzig", "type": "Waldorfschule", "isPrivate": true },
    { "id": 58, "name": "Friedrich-Arnold-Brockhaus-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 59, "name": "Friedrich-Schiller-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 60, "name": "Georg-Christoph-Lichtenberg-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 61, "name": "Gerda-Taro-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 62, "name": "Goethe-Gymnasium Leipzig", "type": "Gymnasium", "isPrivate": false },
    { "id": 63, "name": "Gustav-Hertz-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 64, "name": "Gymnasium Engelsdorf", "type": "Gymnasium", "isPrivate": false },
    { "id": 65, "name": "Humboldt-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 66, "name": "Immanuel-Kant-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 67, "name": "Johanna-Moosdorf-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 68, "name": "Johannes-Kepler-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 69, "name": "Karl Schubert Schule Leipzig - Freie Waldorfschule", "type": "Waldorfschule", "isPrivate": true },
    { "id": 70, "name": "Leibnizschule", "type": "Gymnasium", "isPrivate": false },
    { "id": 71, "name": "Louise-Otto-Peters-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 72, "name": "Marie-Curie-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 73, "name": "Max-Klinger-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 74, "name": "Neue Nikolaischule", "type": "Gymnasium", "isPrivate": false },
    { "id": 75, "name": "Rahn Education Musikalisch-Sportliches Gymnasium", "type": "Gymnasium", "isPrivate": true },
    { "id": 76, "name": "Robert-Schumann-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 77, "name": "Sächsisches Landesgymnasium für Sport Leipzig", "type": "Gymnasium", "isPrivate": false },
    { "id": 78, "name": "Schule am Palmengarten", "type": "Gymnasium", "isPrivate": false },
    { "id": 79, "name": "Schule Hauptbahnhof-Westseite", "type": "Gymnasium", "isPrivate": false },
    { "id": 80, "name": "Schule Ihmelsstraße", "type": "Gymnasium", "isPrivate": false },
    { "id": 81, "name": "Schule Schraderhaus", "type": "Gymnasium", "isPrivate": false },
    { "id": 82, "name": "Thomasschule", "type": "Gymnasium", "isPrivate": false },
    { "id": 83, "name": "Werner-Heisenberg-Schule", "type": "Gymnasium", "isPrivate": false },
    { "id": 84, "name": "Wilhelm-Ostwald-Schule", "type": "Gymnasium", "isPrivate": false },
    // Gemeinschaftsschulen
    { "id": 85, "name": "Leipziger Modellschule Gemeinschaftsschule", "type": "Gemeinschaftsschule", "isPrivate": true },
    { "id": 86, "name": "Schule am Dösner Weg - Gemeinschaftsschule der Stadt Leipzig", "type": "Gemeinschaftsschule", "isPrivate": false },
]

export const MAX_HOBBIES = 5

export const MAX_BYTES = 5 * 1024 * 1024

export const BUCKET = 'avatars'